In [2]:
import numpy as np

np.random.seed(42)

R = np.array([
    [5, 3, 0, 1, 4],
    [4, 0, 2, 0, 5],
    [0, 1, 5, 3, 0],
    [2, 0, 0, 4, 3],
    [3, 4, 1, 0, 2]
], dtype=float)

print("Исходная матрица оценок R (5×5):")
print(R)
print(f"Количество ненулевых элементов: {np.count_nonzero(R)} из {R.size}")
print()


n_users, n_items = R.shape 
d = 3

P = np.random.randn(n_users, d) * 0.1 
Q = np.random.randn(d, n_items) * 0.1

print(f"Матрица P (пользователи × латентные признаки): форма {P.shape}")
print(P)

print(f"Матрица Q (латентные признаки × товары): форма {Q.shape}")
print(Q)


R_pred = P @ Q

print("Предсказанная матрица R_pred = P × Q:")
print(np.round(R_pred, 4))
print()

mask = R != 0

R_observed = R[mask]
R_pred_observed = R_pred[mask]


mse = np.mean((R_observed - R_pred_observed) ** 2)

print("Результаты")
print(f"Количество известных оценок: {np.sum(mask)}")
print(f"Среднеквадратическая ошибка (MSE) по ненулевым элементам: {mse:.6f}")
print(f"RMSE: {np.sqrt(mse):.6f}")
print()

print("Детали по известным оценкам:")
print(f"{'Индекс':<10} {'R (истина)':<12} {'R_pred':<12} {'Ошибка^2':<12}")

indices = np.where(mask)
for i, (row, col) in enumerate(zip(indices[0], indices[1])):
    true_val = R[row, col]
    pred_val = R_pred[row, col]
    error_sq = (true_val - pred_val) ** 2
    print(f"[{row},{col}]:      {true_val:<12.4f} {pred_val:<12.4f} {error_sq:<12.6f}")

Исходная матрица оценок R (5×5):
[[5. 3. 0. 1. 4.]
 [4. 0. 2. 0. 5.]
 [0. 1. 5. 3. 0.]
 [2. 0. 0. 4. 3.]
 [3. 4. 1. 0. 2.]]
Количество ненулевых элементов: 17 из 25

Матрица P (пользователи × латентные признаки): форма (5, 3)
[[ 0.04967142 -0.01382643  0.06476885]
 [ 0.15230299 -0.02341534 -0.0234137 ]
 [ 0.15792128  0.07674347 -0.04694744]
 [ 0.054256   -0.04634177 -0.04657298]
 [ 0.02419623 -0.19132802 -0.17249178]]
Матрица Q (латентные признаки × товары): форма (3, 5)
[[-0.05622875 -0.10128311  0.03142473 -0.09080241 -0.14123037]
 [ 0.14656488 -0.02257763  0.00675282 -0.14247482 -0.05443827]
 [ 0.01109226 -0.11509936  0.0375698  -0.06006387 -0.02916937]]
Предсказанная матрица R_pred = P × Q:
[[-0.0041 -0.0122  0.0039 -0.0064 -0.0082]
 [-0.0123 -0.0122  0.0037 -0.0091 -0.0196]
 [ 0.0018 -0.0123  0.0037 -0.0225 -0.0251]
 [-0.0104  0.0009 -0.0004  0.0045 -0.0038]
 [-0.0313  0.0217 -0.007   0.0354  0.012 ]]

Результаты
Количество известных оценок: 17
Среднеквадратическая ошибка (MSE) по